config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'
  get    'help'    => 'static_pages#help'

  get    'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :bookmarks, only: %i[new destroy]
  resources :books do
    resources :sections, only: %i[index create]
    
    member do
      get 'upload'
      get 'galley'
      post 'print'
      get 'illustrated'
      post 'i9d_print'
    end
  end

  get 'books/:id/:location', to: 'books#show', as: :open_book 
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookmarks
  has_many :books, through: :bookmarks

  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, 
            presence: true, 
            length: { maximum: 50 }, 
            format: { with: VALID_EMAIL_REGEX }, 
            uniqueness: { case_sensitive: false }
  
  has_secure_password
  
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  skip_before_action :require_admin, except: :destroy
  before_action :find_user_or_redirect, only: %i[show edit update destroy]
  before_action :require_owner, only: %i[edit update]
  
  def index
    @users = User.all
    @title = { subtitle: 'All Users' }
  end

  def new
    @user = User.new
    @title = { subtitle: 'Sign up for spineless' }
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'That was easy. Happy reading!'
      redirect_to @user
    else
      @title = { subtitle: 'Sign up for spineless' }
      render 'new'
    end
  end
  
  def show
    @title = { subtitle: "About #{@user.name}" }
  end

  def edit
    @title = { subtitle: "Edit #{@user.name}" }
  end

  def update
    if @user.update(user_params)
      redirect_to @user
      flash[:success] = 'Changes to your profile have been saved.'
    else
      @title = { subtitle: "Edit #{@user.name}" }
      render 'edit'
    end
  end

  def destroy
    user_name = @user.name
    
    if @user.destroy
      flash[:success] = "User #{user_name} has been deleted."
    else
      flash[:error] = "User #{user_name} could not be deleted."
    end
    
    redirect_back fallback_location: users_url
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  # Before filters
  def find_user_or_redirect
    if User.exists?(params[:id])
      @user = User.find(params[:id])
    else
      flash[:danger] = 'The requested page was not found.'
      redirect_back fallback_location: users_path
    end
  end
  
  def require_owner
    return true if current_user?(@user)
    flash[:danger] = 'You do not have permission to do that.'
    redirect_back fallback_location: current_user
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<%= render partial: 'shared/error_messages', locals: { resource: @user } %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation, 'Password Confirmation' %>
    <%= f.password_field :password_confirmation %>
  </p>

  <p>
    <%= f.submit submit_btn_text, class: 'btn' %>
    <%= link_to 'Cancel', user_path(@user) if @user.persisted? %>
  </p>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td>
    <%= link_to user.name, user %>
  </td>
  <td>
    <ul class="bookmarks left-align">
      <% user.books.uniq.each do |book| %>
        <%= tag.li link_to(book.title, book) %>
      <% end %>
    </ul>
  </td>
  <td>
    <%= link_to 'delete', user, method: :delete, data: { confirm: "Are you sure you want to delete #{user.name} permanently?" } if current_user.admin? && !current_user?(user) %>
  </td>
</tr>

app/views/users/edit.html.erb
<h2><%= @title[:subtitle] %></h2>
<%= render partial: 'users/form', locals: { submit_btn_text: 'Save Changes' } %>

app/views/users/index.html.erb
    <h2><%= @title[:subtitle] %> (<%= @users.count %>)</h2>

    <table class="app_index">
      <thead>
        <tr>
          <th>User</th>
          <th>Currently Reading</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
        <%= render user %>
      <% end %>
      </tbody>
    </table>

app/views/users/new.html.erb
<h2><%= @title[:subtitle] %></h2>
<%= render partial: 'users/form', locals: { submit_btn_text: 'Sign up' } %>

app/views/users/show.html.erb
<section id="profile">
  <h2><%= @title[:subtitle] %></h2>
  <table class="user-profile">
    <tbody>
      <tr>
        <th>Name:</th>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <th>Joined:</th>
        <td><%= @user.created_at.strftime('%B %Y') %></td>
      </tr>
      <% if current_user?(@user) %>
      <tr>
        <th>Bookmarks (<%= @user.bookmarks.count %>):</th>
        <td>
          <ul class="bookmarks">
          <% @user.bookmarks.order('created_at DESC').each do |bookmark| %>
          <li>
            <%= render bookmark %>
            <%= link_to 'delete', bookmark, method: :delete, class: 'bookmark-delete', data: { confirm: 'Are you sure you want to delete this bookmark?' } %>
          </li>
          <% end %>
          </ul>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% if current_user.admin? && current_user?(@user) %>
    <p><%= link_to 'New Book', new_book_path, class: 'btn' %></p>
    <p><%= link_to 'Manage Books', books_path, class: 'btn' %></p>
  <% end %>
  <% if current_user?(@user) %>
    <p><%= link_to 'Edit Profile', edit_user_path(current_user), class: 'btn' %></p>
  <% end %>
  <p><%= link_to 'All Users', users_path, class: 'btn' %></p>
</section>