config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'
  get    'help'    => 'static_pages#help'

  get    'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :bookmarks, only: %i[new destroy]
  resources :books do
    resources :sections, only: %i[index create]
    
    member do
      get 'upload'
      get 'galley'
      post 'print'
      get 'illustrated'
      post 'i9d_print'
    end
  end

  get 'books/:id/:location', to: 'books#show', as: :open_book 
end

app/models/book.rb
include ApplicationHelper

class Book < ApplicationRecord
  has_many :sections, dependent: :destroy
  has_many :bookmarks
  has_many :users, through: :bookmarks

  scope :featured_not_hidden, -> { where(featured: 1, hidden: 0) }
  scope :not_featured_not_hidden, -> { where(featured: 0, hidden: 0) }

  validates :title, :author, :cover_image_url, presence: true
  
  before_save :update_chapters_count, 
              unless: proc { |book| book.chapters_count.eql?(book.sections.chapters.count) }

  SKIPS = 4
  CHARACTERS_PER_PAGE = 3500
  
  def location_in_range(location = 0)
    location = location.to_i >= 0 ? location.to_i : 0
    max_number_of_locations > location ? location : (max_number_of_locations - 1)
  end
  
  def scroll_in_range(scroll)
    scroll ||= 0 
    scroll = scroll.tr('_', '.') if scroll.respond_to? :tr
    scroll = scroll.to_d
    scroll = scroll >= 0 ? scroll : 0
    scroll <= 100 ? scroll : 100
  end
  
  def progress_with_scroll(location, scroll)
    progress_start(location) + (scroll * 0.01 * section_progress_points(location)).to_i
  end

  def progress_start(location)
    text_read_length = completed_sections(location).map { |section| section.text.length }.reduce(:+).to_i
    text_read_length * 100 / to_valid_dividend(text_length)
  end
  
  def section_progress_points(location)
    if main_text?(location)
      get_section_from_location(location).text.length * 100.0 / to_valid_dividend(text_length)
    else 
      0
    end
  end
  
  def completed_sections(location)
    completed_sections?(location) ? sections.first(location - SKIPS) : []
  end
  
  def max_number_of_locations
    sections_count + SKIPS
  end
  
  def main_text?(location)
    location >= SKIPS
  end
  
  def completed_sections?(location)
    location > SKIPS
  end
  
  def get_section_from_location(location)
    order = location - SKIPS + 1
    get_section_from_order(order)
  end
  
  def get_section_from_order(order)
    sections.with_order(order).first if sections.with_order(order).count.positive?
  end
  
  def sample_text
    return '' if sections.empty?
    sample_sections.first(2).last.clean_sample
  end
  
  def sample_editor_texts
    sample_sections.first(6).map(&:clean_sample)
  end
  
  def background_image
    "background-image: url(#{background_image_url}); background-size: auto;" if background_image_url.present?
  end

  private
  
  def sample_sections
    if sections.sample_worthy.count <= 1
      sections
    else
      sections.sample_worthy.order(:order)
    end
  end
  
  def update_chapters_count
    self.chapters_count = sections.chapters.count
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :require_login, only: %i[show galley print illustrated i9d_print]
  skip_before_action :require_admin, only: %i[show galley print illustrated i9d_print]
  before_action :find_book_or_redirect, except: %i[index new create]
  
  POSITIONS_TO_PAGE_POSITION = { 'Front' => (0..1), 'Back' => (2..3) }

  def index
    @books = Book.all
    @title = { subtitle: 'Manage Books' }
  end

  def new
    @book = Book.new
    @title = { subtitle: 'New Book' }
  end

  def create
    @book = Book.new(book_params)
    
    if @book.save
      flash[:success] = "#{@book.title} has been added."
      redirect_to upload_book_path(@book)
    else
      @title = { subtitle: 'New Book' }
      render 'new'
    end
  end

  def show 
    @location = @book.location_in_range(params[:location])
    @scroll = @book.scroll_in_range(params[:scroll])
    @section = @book.get_section_from_location(@location) if @book.main_text?(@location) 
    @title = { title: @book.title, subtitle: use_custom_page_subtitle? ? @section.index_title : @book.author }
  end

  def edit
    @title = { subtitle: "Edit #{@book.title}" }
  end

  def update
    @title = { subtitle: "Edit #{@book.title}" }
    flash[:success] = "#{@book.title} has been updated." if @book.update(book_params)
    render 'edit'
  end

  def upload
    @title = { subtitle: "Upload #{@book.title}" }
  end

  def destroy
    if @book.destroy
      flash[:success] = "The book #{@book.title} was deleted."
    else
      flash[:error] = "The book #{@book.title} could not be deleted." 
    end
    redirect_to books_url
  end
  
  def galley
    @title = { subtitle: "#{@book.title} - Galleys" }
    render layout: 'galley'
  end
  
  def print
    @page_height = params[:page_height].to_i
    @title = { subtitle: "#{@book.title} - Print #{params[:position]}" }
    @pages = processed_pages
    @single_images, @multiple_images = processed_images
    render layout: 'galley'
  end
  
  def illustrated
    @title = { subtitle: "#{@book.title} - Galleys" }
    render layout: 'galley'
  end
  
  def i9d_print
    @page_height = params[:page_height].to_i
    @title = { subtitle: "#{@book.title} - Print #{params[:position]}" }
    @pages = processed_pages
    @single_images, @multiple_images = processed_images
    render layout: 'galley'
  end
  
  private
  
  def book_params
    params.require(:book).permit(
      :title, :author, :subtitle, :hidden, :featured, :logo_url, :copyright, :epigraph, :sample,
      :cover_image_url, :background_image_url, :text_length, section_attributes: %i[id title]
    )
  end
  
  def use_custom_page_subtitle?
    @section && @section.indexable?
  end
  
  def processed_pages # sort page data passed by galley.js
    return [] if params[:pages].nil? || params[:position].nil? || !POSITIONS_TO_PAGE_POSITION.key?(params[:position])

    pages = JSON.parse(params[:pages])
    pages = pages.select { |page| page && position_matches?(page, params[:position]) } 
    pages.sort_by { |page| get_sort_order(page) }
  end
  
  def processed_images 
    return [[], []] if params[:images].nil?
    sorted_images(JSON.parse(params[:images]))
  end
  
  def sorted_images(images)
    image_srcs = images.map { |img| img['src'] }
    single_images, multiple_images = images.partition { |img| image_srcs.count(img['src']) == 1 } 
    
    [single_images, 
     multiple_images.map { |img| img.merge('n' => sorted_images_of_type(images, img).index(img) + 1) }]
  end
  
  def sorted_images_of_type(images, image)
    images.select { |img| same_container_and_section?(img, image) }.sort_by { |img| img['n'].to_i }
  end
  
  def same_container_and_section?(image1, image2)
    image1['tagType'] == image2['tagType'] && image1['section_order'] == image2['section_order']
  end
    
  def position_matches?(page, position)
    POSITIONS_TO_PAGE_POSITION[position].include?(page['page_position'])
  end
    
  def get_sort_order(page)
    ((page['signature'] - 1) * 32) + ((page['signature_order'] - 1) * 4) + page['page_position']
  end

  # Before filters
  def find_book_or_redirect
    if Book.exists?(params[:id])
      @book = Book.find(params[:id])
    else
      redirect_back fallback_location: root_url
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
  PAGE_POSITIONS = %w[FL FR BL BR].freeze
  
  def link_to_next(book, location) 
    return nil if location + 1 >= book.max_number_of_locations
    link_to next_icon, open_book_path(book, location + 1), id: 'next-btn', rel: 'Next'
  end
  
  def link_to_previous(book, location) 
    return nil if location <= 0
    path_options = location <= Book::SKIPS ? {} : { scroll: 100 }
    link_to previous_icon, open_book_path(book, location - 1, path_options), id: 'back-btn', rel: 'Back'
  end
  
  def next_icon
    nav_icon('M5 0 L 15 15 L 5 30', 'M25 0 L 35 15 L 25 30')
  end
  
  def previous_icon
    nav_icon('M15 0 L 5 15 L 15 30', 'M35 0 L 25 15 L 35 30')
  end
  
  def nav_icon(path1_d, path2_d)
    path1 = tag.path('', d: path1_d)
    path2 = tag.path('', d: path2_d)
    tag.svg [path1, path2].join.html_safe, width: 40, height: 30, viewBox: '0 0 40 30', xmlns: 'http://www.w3.org/2000/svg', class: 'arrow'
  end
  
  def sidebar_text(page) 
    if page
      [
        'S' + page['signature'].to_s,
        'So' + page['signature_order'].to_s,
        PAGE_POSITIONS[page['page_position']],
        '--' + page['page_num'].to_s
      ].join('-')
    else
      '[sidebar]'
    end
  end

  def rendered_text_div_tag(page) 
    section = @book.get_section_from_order(page['order'])
    return nil unless section
    div_style = 'margin-top:' + (-1 * @page_height * page['pages_before']).to_s + 'px'
    content_tag(:div, section.text.html_safe, class: 'rendered-text', style: div_style)
  end
end

app/views/books/_book.html.erb
<tr>
  <td>
      <%= link_to book.title, book %>
  </td>
  <td>
      <%= book.author %>
  </td>
  <td>
      <%= book.chapters_count %> Chapters<br /> 
      <%= number_with_delimiter(book.text_length) %> Characters
  </td>
  <td>
      <%= link_to 'edit', edit_book_path(book) %> | 
      <%= link_to 'upload', upload_book_path(book) %> | 
      <%= link_to "delete", book, method: :delete, data: { confirm: "Are you sure you want to delete #{book.title} permanently?" } %>
  </td>
</tr>

app/views/books/_bookmark_links.html.erb
              <li>
                <%= link_to 'Get Bookmark', request.original_url.html_safe, id: 'bookmark' %>
              </li>
              <%= tag.li(link_to('Save Bookmark', new_bookmark_path(book_id: @book.id, location: @location, scroll: Bookmark.new(scroll: @scroll).safe_scroll), id: 'new-bookmark')) if logged_in? %>

app/views/books/_copyright_example.html.erb
        <div class="example-markup">
            <p>Example: </p>
            <pre><%= '<div class="cc-license">
    <p>
        This work is licensed under a license.
    </p>
</div>' %>
            </pre>
        </div>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
<%= render partial: 'shared/error_messages', locals: { resource: @book } %>

	<p>
    <%= f.label :title %>
    <%= f.text_field :title %>
	</p>

	<p>
    <%= f.label :author %>
    <%= f.text_field :author %>
	</p>

	<p>
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
	</p>

	<p>
    <%= f.label :featured %>
    <%= f.check_box :featured %>
	</p>

	<p>
    <%= f.label :hidden %>
    <%= f.check_box :hidden %>
	</p>

	<p>
    <%= f.label :logo_url %>
    <%= f.text_field :logo_url %>
	</p>

	<p>
    <%= f.label :cover_image_url %>
    <%= f.text_field :cover_image_url %>
	</p>

	<p>
    <%= f.label :background_image_url %>
    <%= f.text_field :background_image_url %>
	</p>

	<p>
    <%= f.label :epigraph %>
    <%= f.text_area :epigraph %>
	</p>

<%= render partial: 'epigraph_example' %>

	<p>
    <%= f.label :copyright %>
    <%= f.text_area :copyright %>
	</p>

<%= render partial: 'copyright_example' %>

  <% if @book.sample %>
    <p>
      <%= f.label :sample %>
      <%= f.text_area :sample %>
    </p>

<%= render partial: 'sample_selector' %>
  <% end %>

  <p>
    <%= f.submit submit_btn_text, class: 'btn' %>
  </p>

  <p class="form-nav-links">
    <%= link_to 'Back to Manage Books', books_path %>
    <% if @book.id %>
    | <%= link_to "Go to #{@book.title}", book_path(@book) %>
    <% end %>
  </p>
<% end %>

app/views/books/_sidebar.html.erb
                <div class="sidebar">
                    <%= sidebar_text %>
                </div>

app/views/books/_title_page.html.erb
            <!-- Title Page -->
            <div class="page" data-order="title">
<%= render partial: 'sidebar', locals: { sidebar_text: sidebar_text } %>
                <div class="rendered-text">
                    <h1><%= @book.title %></h1>
                    <h2 class="author">by <%= @book.author %></h2>
                    <p class="buffcenter"><%= @book.subtitle %></p>
                </div>
            </div>

app/views/books/_toc_and_progress.html.erb
                    <li class="toc">
                      <span>Table of Contents</span>
                      <ul class="menu">
                        <li><%= link_to 'Cover', open_book_path(@book, 0) %></li>
                        <% @book.sections.chapters.order(:order).each do |section| %>
                          <li><%= link_to section.index_title, open_book_path(@book, section.book_location) %></li>
                        <% end %>
                      </ul>
                    </li>
                    <div id="progress-bar"><span id="progress"></span></div>
                    <div id="progress-percent"></div>

app/views/books/edit.html.erb
<h2>Edit</h2>
<h3><%= @book.title %></h3>
<%= render partial: 'books/form', locals: { submit_btn_text: 'Save Changes' } %>

app/views/books/galley.html.erb
<%= stylesheet_link_tag 'galley', media: 'all' %>

<div class="screen-only centered">
    <h3><%= @book.title %> - Galley Preview</h3>
    <%= form_tag method: :post, action: :print do %>
        <%= hidden_field_tag :images %>
        <%= hidden_field_tag :pages %>
        <%= hidden_field_tag :line_height, 20 %>
        <%= hidden_field_tag :page_height, 680 %>
        <p>
            <%= label_tag :position, 'Position:' %>
            <%= select_tag :position, options_for_select([['Front', 'Front'], ['Back', 'Back']]) %>
        </p>
        <p>
            <%= submit_tag :print, disabled: true, id: 'print-submit'  %>
        </p>
    <% end %>
</div>
<div id="ebook">
<%= render partial: 'title_page', locals: { sidebar_text: sidebar_text(nil) } %>
<%= render partial: 'epigraph_page', locals: { sidebar_text: sidebar_text(nil) } %>
    <!-- Get text from database in order -->
    <%- @book.sections.order(:order).each do |section| %>
        <div class="page" data-order="<%= section.order %>">
<%= render partial: 'sidebar', locals: { sidebar_text: sidebar_text(nil) } %>
            <div class="rendered-text">
                <%= section.text.html_safe %>
            </div>
        </div>
    <%- end %>
</div>
<%= javascript_include_tag 'galley' %>

app/views/books/illustrated.html.erb
<%= stylesheet_link_tag 'illustrated', media: 'all' %>

<div class="screen-only centered">
    <h3><%= @book.title %> - Galley Preview</h3>
    <%= form_tag method: :post, action: :i9d_print do %>
        <%= hidden_field_tag :images %>
        <%= hidden_field_tag :pages %>
        <%= hidden_field_tag :line_height, 20 %>
        <%= hidden_field_tag :page_height, 680 %>
        <p>
            <%= label_tag :position, 'Position:' %>
            <%= select_tag :position, options_for_select([['Front', 'Front'], ['Back', 'Back']]) %>
        </p>
        <p>
            <%= submit_tag :print, disabled: true, id: 'print-submit'  %>
        </p>
    <% end %>
</div>
<div id="ebook">
<%= render partial: 'title_page', locals: { sidebar_text: sidebar_text(nil) } %>
<%= render partial: 'epigraph_page', locals: { sidebar_text: sidebar_text(nil) } %>
    <!-- Get text from database in order -->
    <%- @book.sections.order(:order).each do |section| %>
        <div class="page" data-order="<%= section.order %>">
<%= render partial: 'sidebar', locals: { sidebar_text: sidebar_text(nil) } %>
            <div class="rendered-text">
                <%= section.text.html_safe %>
            </div>
        </div>
    <%- end %>
</div>
<%= javascript_include_tag 'galley' %>

app/views/books/index.html.erb
    <h2><%= @title[:subtitle] %> (<%= @books.count %>)</h2>

    <table class="app_index">
      <thead>
        <tr>
          <th>Title</th>
          <th>Author</th>
          <th>Counts</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
      <% @books.each do |book| %>
        <%= render book %>
      <% end %>
      </tbody>
    </table>

    <p><%= link_to 'New Book', new_book_path, class: 'btn' %></p>
    <p><%= link_to 'View Profile', user_path(current_user), class: 'btn' %></p>
    <p><%= link_to 'All Users', users_path, class: 'btn' %></p>

app/views/books/new.html.erb
<h2><%= @title[:subtitle] %></h2>
<%= render partial: 'books/form', locals: { submit_btn_text: 'Create Book' } %>

app/views/books/print.html.erb
<%= stylesheet_link_tag 'galley', media: 'all' %>

<style>
<% @single_images.each do |image| %>
  #ebook img[src='<%= image['src'] %>'] { 
    <%= render_css(['height', 'margin_top', 'margin_bottom'], image) %>
  }
<% end %>

<% @multiple_images.each do |image| %>
  #ebook .order_<%= image['section_order'] %> <%= image['tagType'].downcase %>:nth-of-type(<%= image['n'] %>) img { 
    <%= render_css(['height', 'margin_top', 'margin_bottom'], image) %>
  }
<% end %>
</style>

<div class="screen-only centered">
    <h3><%= @title[:subtitle] %></h3>
    <p><%= link_to 'Back to Preview', galley_book_path(@book) %></p>
</div>
<div id="ebook">
    <%- @pages.each_with_index do |page, index| %>
        <%= %(<div class="spread clearfix">).html_safe if index.even? %>
        <% case page['order'] %>
            <% when 'title' %>
<%= render partial: 'title_page', locals: { sidebar_text: sidebar_text(page) } %>
            <% when 'epigraph' %>
<%= render partial: 'epigraph_page', locals: { sidebar_text: sidebar_text(page) } %>
            <% when 'blank' %>
<%= render partial: 'blank_page', locals: { sidebar_text: sidebar_text(page) } %>
            <% else %>
            <div class="page order_<%= page['order'] %>">
<%= render partial: 'sidebar', locals: { sidebar_text: sidebar_text(page) } %>
              <%= rendered_text_div_tag(page) %>
            </div>
        <% end %>
        <%= %(</div>).html_safe if index.odd? %>
    <%- end %>
</div>

app/views/books/show.html.erb
    <% content_for :page_styles do %>
      body.books.show { <%= @book.background_image %> }
    <% end %>

     <div id="scroll-wrap">
        <div id="ebook">
          <% case @location %>
          <% when 0 %>
            <p>
              <figure>
                <%= image_tag @book.cover_image_url, alt: @book.title, class: 'book-cover' %>
              </figure>
            </p>
          <% when 1 %>
            <h2><%= @book.title %></h2>
            <h3 class="author">by <%= @book.author %></h3>
            <p class="buffcenter"><%= @book.subtitle %></p>
          <% when 2 %>
            <%= @book.epigraph.html_safe if @book.epigraph %>
          <% when 3 %>
            <%= @book.copyright.html_safe if @book.copyright %>
          <% else %>
            <%= @section.text.html_safe if @section %>
          <% end %>
        </div>
      </div>
      <div id="book-nav">
        <nav class="up">
          Scroll Up
        </nav>
        <nav class="down">
          Scroll Down
        </nav>
      </div>
      <%= link_to_previous(@book, @location) %>
      <%= link_to_next(@book, @location) %>

    <% content_for :before_body_close do %>
      <!-- Lightbox -->
      <div id="lightbox">
        <span class="close">x</span>
      </div>
<%= render 'shared/books_js' %>
    <% end %>