config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'
  get    'help'    => 'static_pages#help'

  get    'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :bookmarks, only: %i[new destroy]
  resources :books do
    resources :sections, only: %i[index create]
    
    member do
      get 'upload'
      get 'galley'
      post 'print'
      get 'illustrated'
      post 'i9d_print'
    end
  end

  get 'books/:id/:location', to: 'books#show', as: :open_book 
end

app/views/layouts/_header.html.erb
<header id="sticky-bar">
  <nav class="clearfix">
    <h1>
    <% if books_show? %>
      <% if @book.logo_url.present? %>
        <%= link_to(image_tag(@book.logo_url, alt: @book.title), book_path(@book)) %>
      <% else %>
        <%= link_to(@book.title, book_path(@book)) %>
      <% end %>
    <% else %>
      <%= link_to(image_tag(asset_path('spineless_logo.png'), alt: 'spineless', class: 'spineless-logo'), root_path) %>
    <% end %>
    </h1>
    <div class="nav-wrapper">
      <ul>
        <li class="main">
            <span>Main Menu</span>
            <ul class="menu">
              <li><%= link_to 'Home', root_path %></li>
              <% if logged_in? %>
                <li><%= link_to 'Profile', current_user %></li>
                <li><%= link_to 'Log out', logout_path, method: :delete %></li>
              
                <% if current_user.admin? %>
                  <li><%= link_to 'Manage books', books_path %></li>
                <% end %>
              <% else %>
                <li><%= link_to 'Login', login_path %></li>
                <li><%= link_to 'Sign up', signup_path %></li>
              <% end %>
              <li><%= link_to 'Help', help_path %></li>
<%= render 'books/bookmark_links' if books_show? %>
            </ul>
        </li>
<%= render 'books/toc_and_progress' if books_show? %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= clean_title %></title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.png' %>
    <%= favicon_link_tag 'favicon.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <style>
    <%= yield :page_styles %>
  </style>
</head>
<body class="<%= render_body_classes %>">
    <div id="wrapper" class="box">
<%= render 'layouts/header' %>
        <% flash.each do |message_type, message| %>
            <div class="clearfix alert alert-<%= message_type %>">
              <%= message %> 
              <span class="close">[x]</span>
            </div>
        <% end %>
        <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= yield :before_body_close %>
</body>
</html>

app/views/layouts/full.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= clean_title %></title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.png' %>
    <%= favicon_link_tag 'favicon.png', rel: 'apple-touch-icon', type: 'image/png' %>
</head>
<body class="<%= render_body_classes %>">
    <div id="wrapper" class="box">
<%= render 'layouts/header' %>
        <% flash.each do |message_type, message| %>
            <div class="clearfix alert alert-<%= message_type %>">
              <%= message %> 
              <span class="close">[x]</span>
            </div>
        <% end %>
    </div>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= yield :before_body_close %>
</body>
</html>

app/views/layouts/galley.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= clean_title %></title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= yield :stylesheet %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.png' %>
    <%= favicon_link_tag 'favicon.png', rel: 'apple-touch-icon', type: 'image/png' %>
</head>
<body class="preview">
    <div id="wrapper">
        <%= yield %>
    </div>
</body>
</html>